version: '3.9'

services:
  app :
    build : .
    container_name: SLBE
    ports : 
    - 8000:8000
    networks:
    - SL
    volumes: 
    - .:/app
    environment:
    - DB_URL=mongodb+srv://aaridwann:Magnumblue234@cluster0.jubwp.mongodb.net/StoryLife?retryWrites=true&w=majority
    - PORT=8000
    - PRIVATE_KEY=ikuhyopy78ec290837-9p2uy232#@Q@QCEAwAKECWecpc;qwo7cn-3p2-c248qw2umomioawe324663w53aw434e2caw354acw32ec413
    - REFRESH_TOKEN=oaisudokqwnelqQWEQPWIPAJS:rupqwoqpowie
    # depends_on:
    # - mongodb2

  # mongodb:
  #   image: mongo
  #   container_name: mongodb2
  #   networks :
  #   - SL
  #   volumes:
  #   - /D/StoryLife/db:/data/db
  #   environment:
  #   - MONGO_INITDB_DATABASE=StoryLife

networks:
  SL:

    
